[package]
name = "hc256-util"
version = "0.2.1"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hc256 = { path = "../hc256" }
base64 = "0.13"
clap = "2.33"